package mpp.jsonprotocol;

public enum RequestType {
    LOGIN, LOGOUT, SAVE_PARTICIPANT, GET_PARTICIPANT_MRU, FIND_ALL_PROBE, FIND_PROBA_BY_ID,
    GET_NR_PARTICIPANTI_INSCRISI, FIND_PARTICIPANTI_BY_PROBA, SAVE_INSCRIERE, GET_NR_PROBE_PARTICIPANT, FIND_UTILIZATOR;
}