package mpp.jsonprotocol;

public enum ResponseType {
    OK, ERROR, LOGIN_SUCCESS, LOGOUT_SUCCESS, PARTICIPANT_SAVED, PARTICIPANT_MRU, ALL_PROBE, PROBA_FOUND,
    NR_PARTICIPANTI_INSCRISI, PARTICIPANTI_BY_PROBA, INSCRIERE_SAVED, NR_PROBE_PARTICIPANT, PARTICIPANT_ADDED, INSCRIERE_ADDED;
}